title: Welcom to Jamie's Home
email: jamie.cui@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Student ... of Computer Security(?)

# Build settings
markdown: kramdown
theme: minima

