title: Welcom to Jamie's Home
email: jamie.cui@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Student ... of Computer Security(?)

github_username:  Jamie2Cui

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

