
title: Welcom to Jamie's Home
email: jamie.cui@outlook.com
description: >- 
  Student ... of Computer Security(?)
baseurl: "/Jamie-Home"
url: "https://jamie2cui.github.io" 

github_username:  Jamie2Cui

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
