
title: Jamie's Home
email: jamie.cui@outlook.com
description: >- 
  Student of Computer Science, Informatics school, University of Edinburgh
baseurl: "/Jamie-Home"
url: "https://jamie-cui.github.io" 

github_username:  Jamie2Cui
permalink: /:title.html

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
