
title: Jamie's Home
email: jamie.cui@outlook.com
description: >- 
  Find Factors, Get Money.
baseurl: "/Jamie-Home"
url: "https://jamie-cui.github.io" 

github_username:  Jamie-Cui
permalink: /:title.html

markdown: kramdown
theme: minima
plugins_dir:
  - jekyll-feed
